### ISSUE TITLE
Add ways to slow food spoil time, there's missing foods, and no modded food support.

### ISSUE THREAD

**Issue by MagmaBro123** [ACGaming/FoodSpoiling#1]
Title.

Like Food Funk, a Freezer would be kinda nice. It also seems MANY of Vanilla's foods have no decay time, and modded food support is non-existent.

![2024-11-03_08 45 22](https://github.com/user-attachments/assets/9ca4e724-fe08-435f-b755-509c0f31c01b)

**Comment by ACGaming** [comment]
Adding preserving containers is not planned, as there are several in commonly utilized food/furniture mods, like fridges from Cooking For Blockheads or MrCrayfish's Furniture Mod.

This mod is primarily designed for modpack creators and thus only contains some example values. Generally, modpack creators would likely want to configure the mod around their utilized ore dictionary names.

However, I can see that the default configuration is somewhat lacking in this regard, going to improve that for the next update.
